// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace LibreDrugstore
{
    [default_interface]
    runtimeclass Checkout : Microsoft.UI.Xaml.Controls.Page
    {
        Checkout();
        Int32 MyProperty;
    }
}
